name: Build and Archive

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Zip Archive
        run: |
          zip -r9 index-wp-mysql-for-speed.zip . \
          -x "composer.json" \
          -x "composer.lock" \
          -x "README.md" \
          -x "CODE-OF-CONDUCT.md" \
          -x "tests/*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: index-wp-mysql-for-speed
          path: index-wp-mysql-for-speed.zip
